

GET http://localhost:3000/api/tarifas/


###

GET http://localhost:3000/api/tarifas/type/Fibra y Móvil

###
GET http://localhost:3000/api/tarifas/speed/600Mb

###

GET http://localhost:3000/api/tarifas/name/Plan Oro

###
GET http://localhost:3000/api/tarifas/gb/libre

###
GET http://localhost:3000/api/tarifas/type/movil/data/Móvil 120GB + ilimitadas

###

###
POST http://localhost:3000/api/tarifas
Content-Type: application/json

{
    "extras": [],
    "type": "Móvil",
    "name": "Plan de Prueba",
    "gb": "libre",
    "minutes": "ilimitadas",
    "price": 25.95
}

###
PUT http://localhost:3000/api/tarifas/662e26cb38a7ec7e6eddcbfe
Content-Type: application/json

{
    "name": "Plan oro",
    "price": 8.95
}

###
DELETE http://localhost:3000/api/tarifas/662fe1ebe23f507ed7248fed